### ISSUE TITLE
.NETStandard 1.3 issue

### ISSUE THREAD

**Issue by powerdude** [xaviergonz/T4Immutable#1]
Hello, 

I'm interested in this class and was trying to use it in a PCL .netStandard 1.3 and it fails to install.  Can you support .NETStandard?

**Comment by xaviergonz** [comment]
Hi.

I just released a new version that should be usable with .net standard 1.1 and higher. However due to current NuGet limitations with these new-style projects you will have to follow some manual steps that aren't needed with old-style (.NET Framework) projects.

PS: If you have any trouble let me know.

Quoting the README.md...

#### New-style (.NET Core, .NET Standard, UWP, Portable Class Libraries...)

Since right now NuGet does not support copying files to the project itself you will need to follow the next steps:
1. Install the T4Immutable nuget package
2. Create a folder in the root of your project named "T4Immutable"
3. Download the T4Immutable sources at https://github.com/xaviergonz/T4Immutable/archive/master.zip
4. Extract the folder _src/content/T4Immutable_ (inside the ZIP) to the _T4Immutable_ folder of your project

"**Build - Transform All T4 Templates**" **won't work**, so you will need to right click the file _T4Immutable/T4Immutable.tt_ and click on "**Run custom tool**" whenever you want to regenerate your templates.

_You will need to do 2 and 3 everytime you update this nuget package._

As soon as NuGet gets better support for this (or someone tells me how to do it) for new-style projects there will be an update to do this automatically like it is done for old-style .NET projects.

**Comment by xaviergonz** [comment]
Just added proper support for .NET Standard 2.0 without so many workarounds, check the docs for more info and feel free to reopen the ticket if it doesn't work :)
